### ISSUE TITLE
Validate input for config name property

### ISSUE THREAD

**Issue by Manuri** [wso2/testgrid#1127]
**Description:**
eg:
```yaml
deploymentConfig:
  deploymentPatterns:
    - name: 'scenario tests'
      description: 'dummy'
      remoteRepository: "https://github.com/ballerina-platform/ballerina-lang.git"
      remoteBranch: "ballerina-scenarios"
      dir: .
      scripts:
        - name: 'default'
          type: SHELL
          file: product-scenarios/deployment-data.sh
```

Above configuration causes the following

```bash
[INFO] : 2019-01-05, 13:33:32 : Preparing workspace for testplan : data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1
[INFO] : 2019-01-05, 13:33:32 :  Creating workspace and builds sub-directories
[data-integration@2] Running shell script
+ rm -r -f /testgrid/testgrid-home/jobs/data-integration/data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1/
+ mkdir -p /testgrid/testgrid-home/jobs/data-integration/data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1
+ mkdir -p /testgrid/testgrid-home/jobs/data-integration/data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1/builds
+ mkdir -p /testgrid/testgrid-home/jobs/data-integration/data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1/workspace
+ cd /testgrid/testgrid-home/jobs/data-integration/data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1/workspace
+ echo Workspace directory content:
Workspace directory content:
+ ls /testgrid/testgrid-home/jobs/data-integration/data-integration_scenario tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1/
ls: cannot access 'tests_OracleJDK-8_MySQL-5.7_Ubuntu-18.04_run1/': No such file or directory
/testgrid/testgrid-home/jobs/data-integration/data-integration_scenario:
script returned exit code 2
```
