### ISSUE TITLE
Cannot create test plan without passing a database type in testgrid.yaml

### ISSUE THREAD

**Issue by VijithaEkanayake** [wso2/testgrid#1140]
**Description:**
Please refer below part of the yaml configuration.
```yaml
# TestGrid Test Configuration Parameters
version: '0.9'
emailToList: "manurip@wso2.com,vijithae@wso2.com"
infrastructureConfig:
  infrastructureProvider: SHELL
  containerOrchestrationEngine: K8S
  includes:
    - Ubuntu-18.04
    - MySQL-5.7
    - OracleJDK-8
```
There are use cases that we don't need to use a database. However we always need to pass database type in the testgrid yaml file to create test plan. Testgrid is not able to generate test plan if we ommit the database type in the yaml file.
