### ISSUE TITLE
AWS region can be configured via infrastructureConfig now.

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#496]
**Description:**
This can be done by setting the inputParameter 'region' under the `infrastructureConfig -> scripts`. 

However, this does not work ATM. We need to look at why this does not happen.

**Affected Product Version:**
0.9.0-m14

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Run `cloudformation-is` with the following testgrid.yaml.
```yaml
version: '0.9'
infrastructureConfig:
  iacProvider: CLOUDFORMATION
  infrastructureProvider: AWS
  containerOrchestrationEngine: None
  parameters:
    - JDK : ORACLE_JDK8
  provisioners:
    - name: 01-two-node-deployment
      description: Provision Infra for a two node IS cluster
      dir: cloudformation-templates/pattern-1
      scripts:
        - name: infra-for-two-node-deployment
          description: Creates infrastructure for a IS two node deployment.
          type: CLOUDFORMATION
          file: pattern-1-with-puppet-cloudformation.template.yml
          inputParameters:
            parseInfrastructureScript: false
            region: us-east-2
            DBPassword: "DB_Password"
            EC2KeyPair: "testgrid-key"
            ALBCertificateARN: "arn:aws:acm:us-east-1:809489900555:certificate/2ab5aded-5df1-4549-9f7e-91639ff6634e"

scenarioConfig:
  scenarios:
    -  "scenario02"
    -  "scenario12"
    -  "scenario21"
```

**Related Issues:**
