### ISSUE TITLE
Introduce job-config.yaml to feed data to testgrid commands

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#529]
**Description:**
ATM, we are feeding loads of inputs into the ./testgrid script as input arguments. This is not scalable as the requirements grow. Hence, we need to introduce a job-config.yaml that contain this information.

Sample log-config.yaml:
```yaml 
relativePaths: true
infrastructureRepository: ./Infrastructure
deploymentRepository: ./Deployment
scenarioTestsRepository: ./Solutions
testgridYamlLocation: ./testgrid.yaml
```

This file will be the input to generate-testplan command. The input for run-testplan is a generated test-plan file. In this case, all the inputs need to be self-contained within the test-plan file.

With this change, the inputs to testgrid commands will be as follows:

```sh
sh testgrid generate-test-plan --product wso2is.local -f ~/git-repos/testgrid/test-scripts/local-is-deployment/job-config.yaml

sh testgrid run-testplan -p wso2is.local -f ~/.testgrid/wso2is.local2/test-plans/test-plan-01.yaml
```

For the first command, you may also pass the parameter '--workingDir' to resolve relative paths in the job-config.yaml properly.

**Affected Product Version:**
0.9.0-m14

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A
