### ISSUE TITLE
testgrid.yaml - Remove duplicated name and description elements

### ISSUE THREAD

**Issue by kasunbg** [wso2/testgrid#821]
**Description:**

'Name' and 'description' tags are Duplicated everywhere in the testgrid.yaml::infrastructureConfig.
![image](https://user-images.githubusercontent.com/936037/41758151-70e549e2-7604-11e8-9b5c-63c62de74250.png)

**Affected Product Version:**
m31

**OS, DB, other environment details and versions:**    
N/A
**Steps to reproduce:**

```yaml
  provisioners:
    - name: 01-single-node-ec2-and-rds-deployment
      description: Provision Infra for running intg tests
      dir: jobs/intg-test-resources
      scripts:
        - name: '01-single-node-ec2-and-rds-deployment'
          description: ''
          type: CLOUDFORMATION
          file: wso2-intg-test-cfn.yaml
          inputParameters:
            parseInfrastructureScript: false
            region: us-east-1
            DBPassword: "DB_Password"
            EC2KeyPair: "testgrid-key"
            ALBCertificateARN: "arn:aws:acm:us-east-1:809489900555:certificate/2ab5aded-5df1-4549-9f7e-91639ff6634e"

```

**Related Issues:**
