### ISSUE TITLE
Add identifiable names to stacks and created instances

### ISSUE THREAD

**Issue by yasassri** [wso2/testgrid#989]
**Description:**

ATM it is hard to identify stacks and differentiate them, so we need to add proper names to stacks associated other resources.

**Comment by pasindujw** [comment]
The stack name is referred from testgrid-yaml file in each job. (The name of the provisioning script is taken as the stack name after appending a Random Number).
eg: 
```
 provisioners:
    - name: ballerina-intg-deployment
      description: Provision Infra for running intg tests
      scripts:
        - name: ' ballerina-intg-deployment'
```
The script name is changed in each PROD and Dev job as to reflects their job-name. As a result, the stacks will have an job-specific name.
